<a href="https://colab.research.google.com/github/msatyasambhav-beep/Machine-Learning/blob/main/TL_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('CustomerChurn.csv')

In [4]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [9]:
df.dropna(how = 'any',inplace = True)

In [10]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [12]:
X = df.drop(['customerID','Churn'],axis = 1)

In [13]:
y = df.Churn.values

In [14]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [15]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [16]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [17]:
#Convert categorical features to numerical --> feature encoding

X = pd.get_dummies(X,columns = ['gender','Partner','Dependents',
                                'PhoneService','MultipleLines','InternetService','OnlineSecurity',
                                'OnlineBackup','DeviceProtection','TechSupport','StreamingTV'
                                ,'StreamingMovies','Contract','PaperlessBilling','PaymentMethod',
                                'MonthlyCharges','TotalCharges'],drop_first=True)

In [18]:
X.head(1)

,SeniorCitizen,tenure,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,TotalCharges_8477.7,TotalCharges_8496.7,TotalCharges_8529.5,TotalCharges_8543.25,TotalCharges_8547.15,TotalCharges_8564.75,TotalCharges_8594.4,TotalCharges_8670.1,TotalCharges_8672.45,TotalCharges_8684.8
0,0,1,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
#Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25)

In [21]:
len(X_train)

5274

In [22]:
len(X_test)

1758

In [23]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [24]:
X_train_sc

array([[ 2.33228653,  0.92176551,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118],
       [-0.42876379,  1.08434977, -1.01644155, ..., -0.01377118,
        -0.01377118, -0.01377118],
       [ 2.33228653, -0.94795348,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118],
       ...,
       [-0.42876379,  0.31207454,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118],
       [-0.42876379,  0.59659699, -1.01644155, ..., -0.01377118,
        -0.01377118, -0.01377118],
       [-0.42876379,  0.06819815,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118]])

In [26]:
X_test

,SeniorCitizen,tenure,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,TotalCharges_8477.7,TotalCharges_8496.7,TotalCharges_8529.5,TotalCharges_8543.25,TotalCharges_8547.15,TotalCharges_8564.75,TotalCharges_8594.4,TotalCharges_8670.1,TotalCharges_8672.45,TotalCharges_8684.8
3330,1,51,True,False,False,True,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
4824,1,72,True,True,False,True,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
2218,0,71,False,True,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6916,0,44,True,False,True,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4018,0,7,False,True,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6862,1,4,False,False,False,True,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
6504,0,3,True,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3539,0,8,True,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4284,1,32,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1833,0,1,True,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

kNN Classifier

In [27]:
#Call the kNN Classifier
from sklearn.neighbors import KNeighborsClassifier

#Instantiate the kNN Classifier
model = KNeighborsClassifier()

#Passing the data to classifier
model.fit(X_train_sc,y_train)

KNeighborsClassifier()

In [29]:
y_pred = model.predict(X_test_sc)

In [30]:
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [31]:
y_test

array(['Yes', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [34]:
#Classification metrics = to check how the model is behaving
from sklearn.metrics import accuracy_score

round(accuracy_score(y_test,y_pred)*100,2)

73.61

#### New data prediction

In [36]:
X_test_sc

array([[ 2.33228653,  0.75918125,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118],
       [ 2.33228653,  1.61274862,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118],
       [-0.42876379,  1.57210256, -1.01644155, ..., -0.01377118,
        -0.01377118, -0.01377118],
       ...,
       [-0.42876379, -0.98859954,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118],
       [ 2.33228653, -0.01309398, -1.01644155, ..., -0.01377118,
        -0.01377118, -0.01377118],
       [-0.42876379, -1.273122  ,  0.9838244 , ..., -0.01377118,
        -0.01377118, -0.01377118]])

In [37]:
X_test.head(1)

,SeniorCitizen,tenure,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,TotalCharges_8477.7,TotalCharges_8496.7,TotalCharges_8529.5,TotalCharges_8543.25,TotalCharges_8547.15,TotalCharges_8564.75,TotalCharges_8594.4,TotalCharges_8670.1,TotalCharges_8672.45,TotalCharges_8684.8
3330,1,51,True,False,False,True,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False

In [38]:
X_test.columns

Index(['SeniorCitizen', 'tenure', 'gender_Male', 'Partner_Yes',
       'Dependents_Yes', 'PhoneService_Yes', 'MultipleLines_No phone service',
       'MultipleLines_Yes', 'InternetService_Fiber optic',
       'InternetService_No',
       ...
       'TotalCharges_8477.7', 'TotalCharges_8496.7', 'TotalCharges_8529.5',
       'TotalCharges_8543.25', 'TotalCharges_8547.15', 'TotalCharges_8564.75',
       'TotalCharges_8594.4', 'TotalCharges_8670.1', 'TotalCharges_8672.45',
       'TotalCharges_8684.8'],
      dtype='object', length=8140)

In [39]:
data = [[0,2,87,178,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1]]

In [45]:

# Transform and predict using the aligned data shape
data_sc = sc.transform(data_aligned)
single = model.predict_proba(data_sc)
print(single)

[[0.8 0.2]]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(